recipe: default.v1

assistant_id: 20250204-124526-green-resource

language: id

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
    intent_tokenization_flag: True
    intent_split_symbol: "_"
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: True
  - name: EntitySynonymMapper 
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.2


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_contact_it_support"
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
