version: '3.1'

services:
  rasa:
    build: .
    container_name: rasa_server
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: rasa run --enable-api --cors "*"

  action_server:
    image: rasa/rasa-sdk:3.6.2
    container_name: action_server
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
